name: Metrics

on:
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics (topics icons)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Mharomoincpass
          template: classic
          filename: metrics.plugin.topics.icons.svg

          # Only show the starred topics icons panel
          base: ""

          plugin_topics: yes
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          plugin_topics_limit: 40
          plugin_topics_icons: yes
